server:
  port: 8084

auth:
  service:
    url: http://localhost:8080

customer:
  service:
    url: http://localhost:8082

product:
  service:
    url: http://localhost:8083

cors:
  allowed-origins: http://localhost:3000